<a href="https://colab.research.google.com/github/abdulabba0/abdulpython/blob/main/AbdulRahim_Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Numpy for Data Analytics**

> ## **What is Numpy**
Numpy stand for Numerical PYTHON, it is a fundamental library for numerical computing in Python. It provide support for large multidimensional array and matrices, along with an etensive collection of mathematical functions to perform operations efficiently.

Numpy is widely use in Data Analytics and Finance, engineering etc.


> ## **Why Use Numpy**


In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


### **Creating a Numpy Array**

In [3]:
# Basic Numpy Array
# creating a numpy array
# vector or 1 dimensional array

arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

### **Array Properties**

In [4]:
# checking the shape of the array
print(f"The shape of the array is:  {arr.shape}")
print(f"Array Dimension:  {arr.ndim}")
print(f"Array Data Type:  {arr.dtype}")

The shape of the array is:  (4,)
Array Dimension:  1
Array Data Type:  int64


In [5]:
# 2 Dimensional Array
arr2 = np.array([
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6]
                 ])

In [6]:
print(f"The shape of the array is:  {arr2.shape}")
print(f"Array Dimension:  {arr2.ndim}")

The shape of the array is:  (4, 3)
Array Dimension:  2


In [7]:
dim_3_array = np.array([
    [[2, 3, 4],
     [4, 5, 6]],
    [[4, 5, 7],
    [3, 6, 7]]
])

In [8]:
print(f"The shape of the array is:  {dim_3_array.shape}")
print(f"Array Dimension:  {dim_3_array.ndim}")

The shape of the array is:  (2, 2, 3)
Array Dimension:  3


### **Different ways of creating an Array in Numpy**

> You can create a numpt array from a
- Python List
- Python Tuple
- Random float array using np.random
- we can create a range of array using  np.arange
- using np.full
- using np.zeros
- using np.linspace
- using np.ones

In [9]:
# creating an array of zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# creating an array of ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# creating an array of certain range of number'
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [12]:
# creating an evenly space array
np.linspace(0, 1, num=100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [13]:
# creating a numpy array using python list

py_list = [1, 2, 3, 4, 5]
np_list = np.array(py_list)
print("Data Type: ", np_list.dtype)
print("Checking data type using python ", type(np_list))

Data Type:  int64
Checking data type using python  <class 'numpy.ndarray'>


In [14]:
# creating a numpy array using python tuple

py_tuple = (1, 2, 3, 4, 5)
np_tuple = np.array(py_tuple)
print("Data Type: ", np_tuple.dtype)
print("Checking data type using python ", type(np_tuple))

Data Type:  int64
Checking data type using python  <class 'numpy.ndarray'>


In [15]:
# creating an array using python rnadom module

rand_mod = np.random.random()
rand_mod

0.8373241621179499

In [16]:
multidim_random = np.random.random((3, 3))
multidim_random

array([[0.78106401, 0.77808253, 0.73415659],
       [0.41593469, 0.48077601, 0.67863844],
       [0.06504252, 0.75831154, 0.99833164]])

In [17]:
# creating random integers
rand_int = np.random.randint(1, 100, size=(3, 3))
rand_int

array([[86, 71, 54],
       [22, 78,  3],
       [33, 58, 48]])

In [18]:
# random samples
np.random.random_sample((4, 3))

array([[0.10483115, 0.40099678, 0.5005931 ],
       [0.05064081, 0.47062643, 0.64029301],
       [0.90979043, 0.66881681, 0.83310409],
       [0.77570398, 0.64250939, 0.26710547]])

In [19]:
# using np.full

full_array = np.full((3, 3), 5)
full_array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### **Array Indexing and Slicing**

In [20]:
# acessing a 1 dimensional array
print("First Element: ", arr[0])
print("Last Element: ", arr[-1])

First Element:  1
Last Element:  4


In [21]:
# acessing index 2 of first dimension and index 2 of second dimension
print("2 : 2 ", rand_int[2][2])
print("2 : 1 ", rand_int[0][2])

2 : 2  48
2 : 1  54


In [22]:
# acessing a 3 dimensional array
np.random.seed(42)
three_dim_arr = np.random.randint(1, 100, size=(3, 4, 4))
three_dim_arr

array([[[52, 93, 15, 72],
        [61, 21, 83, 87],
        [75, 75, 88, 24],
        [ 3, 22, 53,  2]],

       [[88, 30, 38,  2],
        [64, 60, 21, 33],
        [76, 58, 22, 89],
        [49, 91, 59, 42]],

       [[92, 60, 80, 15],
        [62, 62, 47, 62],
        [51, 55, 64,  3],
        [51,  7, 21, 73]]])

### Array Slicing

In [23]:
three_dim_arr[:2]

array([[[52, 93, 15, 72],
        [61, 21, 83, 87],
        [75, 75, 88, 24],
        [ 3, 22, 53,  2]],

       [[88, 30, 38,  2],
        [64, 60, 21, 33],
        [76, 58, 22, 89],
        [49, 91, 59, 42]]])

In [24]:
three_dim_arr[:2, :2, :2]

array([[[52, 93],
        [61, 21]],

       [[88, 30],
        [64, 60]]])

In [25]:
print("Equal to : ", three_dim_arr[three_dim_arr % 2 == 0])
print("Greater than : ", three_dim_arr[three_dim_arr > 2])
print("Less than : ", three_dim_arr[three_dim_arr < 4])

Equal to :  [52 72 88 24 22  2 88 30 38  2 64 60 76 58 22 42 92 60 80 62 62 62 64]
Greater than :  [52 93 15 72 61 21 83 87 75 75 88 24  3 22 53 88 30 38 64 60 21 33 76 58
 22 89 49 91 59 42 92 60 80 15 62 62 47 62 51 55 64  3 51  7 21 73]
Less than :  [3 2 2 3]


### **Array Operations**
> Basic Operation
- Addition
- Subtraction
- Multiplication
- Division

> Statistical Operation
- Mean
- Median
- Mode
- sum
- standard deviation
- sum

> Trigonometry Operation
- sin
- cosine
- Tangent

> Others
- log
- exponent
- round
- ceil
- floor

### **Simple Operation**

In [26]:
op1 = np.array([1, 2, 3, 4])
op2 = np.array([5, 6, 7, 8])

In [27]:
# Addition

print("Addition: ", op1 + op2)

Addition:  [ 6  8 10 12]


In [28]:
# Subtraction
print("Subtraction: ", op1 - op2)

Subtraction:  [-4 -4 -4 -4]


In [29]:
# Multiplication
print("Multiplication: ", op1 * op2)

Multiplication:  [ 5 12 21 32]


In [30]:
# Division
print("Multiplication: ", op1 / op2)

Multiplication:  [0.2        0.33333333 0.42857143 0.5       ]


In [31]:
# Division
print("Multiplication: ", op1 / op2)

Multiplication:  [0.2        0.33333333 0.42857143 0.5       ]


In [32]:
# Division
print("Multiplication: ", op1 ** op2)

Multiplication:  [    1    64  2187 65536]


### Matrix Multiplication

In [33]:
matrix_1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix_2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])


In [34]:
# matrix multiplication
np.dot(matrix_1, matrix_2)

array([[ 58,  64],
       [139, 154]])

In [35]:
# matrix multiplication
matrix_1 @ matrix_2

array([[ 58,  64],
       [139, 154]])

In [36]:
# matrix multiplication
matrix_1.dot(matrix_2)

array([[ 58,  64],
       [139, 154]])

### **Statistical Operation**


In [37]:
# mean
np.random.seed(42)
stat_arr = np.random.randint(1, 100, size=(100, 6))
stat_arr

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24],
       [ 3, 22, 53,  2, 88, 30],
       [38,  2, 64, 60, 21, 33],
       [76, 58, 22, 89, 49, 91],
       [59, 42, 92, 60, 80, 15],
       [62, 62, 47, 62, 51, 55],
       [64,  3, 51,  7, 21, 73],
       [39, 18,  4, 89, 60, 14],
       [ 9, 90, 53,  2, 84, 92],
       [60, 71, 44,  8, 47, 35],
       [78, 81, 36, 50,  4,  2],
       [ 6, 54,  4, 54, 93, 63],
       [18, 90, 44, 34, 74, 62],
       [14, 95, 48, 15, 72, 78],
       [87, 62, 40, 85, 80, 82],
       [53, 24, 26, 89, 60, 41],
       [29, 15, 45, 65, 89, 71],
       [ 9, 88,  1,  8, 88, 63],
       [11, 81,  8, 35, 35, 33],
       [ 5, 41, 28,  7, 73, 72],
       [12, 34, 33, 48, 23, 62],
       [88, 37, 99, 44, 86, 91],
       [35, 65, 99, 47, 78,  3],
       [ 1,  5, 90, 14, 27,  9],
       [79, 15, 90, 42, 77, 51],
       [63, 96, 52, 96,  4, 94],
       [23, 15, 43, 29, 36, 13],
       [32, 71, 59, 86, 28, 66],
       [42, 45, 62, 57,  6, 28],
       [28

In [38]:
# mean
stat_arr.mean()

np.float64(49.86)

In [39]:
# Median
np.median(stat_arr)

np.float64(50.5)

In [40]:
import pandas as pd

In [41]:
pro = ['A', 'B', 'C', 'D']
pro

['A', 'B', 'C', 'D']

In [42]:
type(pro)

list

In [43]:
pro_catergoies = pd.Series(pro)

In [44]:
pro_catergoies

0    A
1    B
2    C
3    D
dtype: object

In [46]:
type(pro_catergoies)

pandas.core.series.Series