<a href="https://colab.research.google.com/github/abdulabba0/abdulpython/blob/main/Abdulrahim_Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Numpy for Data Analytics**

>## **What is Numpy**
Numpy stands for Numerical Python, is is a fundamental library for numerical computing in python. It provide support for large multidimensional array and matrices, along with an extensive collection of mathematical functions to perform operations efficiently.

Numpy is widely use in Data analytics and Finance, engineering, etc.

In [ ]:
import numpy as np

np.__version__

'2.0.2'

## Creating a Numpy Array

In [ ]:
# Basic numpy Array
# creating a numpy array

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

Array Properties

In [ ]:
# Checking the shape of the Array
print(f"The shape of the array is {arr.shape}")
print(f"Array dimension is {arr.ndim}")
print(f"Data type of the array is {arr.dtype}")

The shape of the array is (4,)
Array dimension is 1
Data type of the array is int64


In [ ]:
arr2 = np.array([[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
                 ]])

In [ ]:
print(f"The shape of the array is {arr2.shape}")
print(f"Array dimension is {arr2.ndim}")

The shape of the array is (1, 3, 4)
Array dimension is 3


# **Different ways of creating an Array in Numpy**

In [ ]:
# creating an array of zeros
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# creating an array of ones
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
# creating a range of arrays
np.arange(1,100,5,)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
# creating an evenly space array
np.linspace(0,1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# creating a numpy array using python

py_list = [1,2,3,4,5]
np_list = np.array(py_list)
print("Data type: ", np_list.dtype)
print("Checking data type using python ", type(np_list))

Data type:  int64
Checking data type using python  <class 'numpy.ndarray'>


In [ ]:
# creating a numpy array using python

py_list = [1,2,3,4,5]
np_list = np.array(py_list)
print("Data type: ", np_list.dtype)
print("Checking data type using python ", type(np_list))

Data type:  int64
Checking data type using python  <class 'numpy.ndarray'>


In [ ]:
# creating a numpy array using python tuple

py_list = [1,2,3,4,5]
np_list = np.array(py_list)
print("Data type: ", np_list.dtype)
print("Checking data type using python tuple ", type(np_list))

In [ ]:
# creating an array using python random module

rand_mod = np.random.random()
rand_mod

0.013144711620482585

In [ ]:
multidim_random = np.random.random((3,3))
multidim_random

array([[0.00636552, 0.58939741, 0.47137764],
       [0.01816593, 0.43574166, 0.8259774 ],
       [0.26904671, 0.01536015, 0.02785341]])

In [ ]:
rand_int = np.random.randint(1, 100, size=(3, 3))
rand_int

array([[27, 28, 35],
       [30,  9, 49],
       [ 8, 30,  7]])

In [ ]:
np.random.random_sample((4,3))


array([[0.38517554, 0.28137238, 0.56418647],
       [0.71425513, 0.19257837, 0.41346153],
       [0.72113228, 0.0523913 , 0.90983306],
       [0.7565323 , 0.24714587, 0.53718435]])

In [ ]:
# using np.full
full_array = np.full((3,3), 5)
full_array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## **Array Indexing and Slicing**

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
# Indexing
print("2 : 2 ", rand_int[2][2])
print("2 : 2 ", rand_int[2][0])

2 : 2  7
2 : 2  8


In [ ]:
# accessing 3 dimensional array
np.random.seed(42) # keep the number for that much times
three_dim_arr = np.random.randint(1, 100, size=(3,4,4))
three_dim_arr

array([[[52, 93, 15, 72],
        [61, 21, 83, 87],
        [75, 75, 88, 24],
        [ 3, 22, 53,  2]],

       [[88, 30, 38,  2],
        [64, 60, 21, 33],
        [76, 58, 22, 89],
        [49, 91, 59, 42]],

       [[92, 60, 80, 15],
        [62, 62, 47, 62],
        [51, 55, 64,  3],
        [51,  7, 21, 73]]])

In [ ]:
# Slicing
three_dim_arr[:2, :2, :2]

array([[[52, 93],
        [61, 21]],

       [[88, 30],
        [64, 60]]])

In [ ]:
# three_dim_arr[three_dim_arr % 2 == 0]
three_dim_arr[three_dim_arr > 10]

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24, 22, 53, 88, 30, 38,
       64, 60, 21, 33, 76, 58, 22, 89, 49, 91, 59, 42, 92, 60, 80, 15, 62,
       62, 47, 62, 51, 55, 64, 51, 21, 73])

### Array Operations

>Basic Operation
*   Addition
*   Subtraction
*   Multiplication
*   Division
*   Exponent

>Statistal Operations
*   Mean
*   Median
*   Mode
*   Sum
*   Standard deviation

>Trigonometry Operations
*   Sin
*   Cosine
*   Tangent

>Others

*   floor









In [ ]:
#Addition
print("Addition ", three_dim_arr + 4)

#Subtraction
print("Subtraction ", three_dim_arr - 10)

#Multiplication
print("Multiplication ", three_dim_arr * 2)

#Division
print("Division ", three_dim_arr / 2)

# np.dot is also mulitiplication
# @ is also mulitiplication

Addition  [[[56 97 19 76]
  [65 25 87 91]
  [79 79 92 28]
  [ 7 26 57  6]]

 [[92 34 42  6]
  [68 64 25 37]
  [80 62 26 93]
  [53 95 63 46]]

 [[96 64 84 19]
  [66 66 51 66]
  [55 59 68  7]
  [55 11 25 77]]]
Subtraction  [[[42 83  5 62]
  [51 11 73 77]
  [65 65 78 14]
  [-7 12 43 -8]]

 [[78 20 28 -8]
  [54 50 11 23]
  [66 48 12 79]
  [39 81 49 32]]

 [[82 50 70  5]
  [52 52 37 52]
  [41 45 54 -7]
  [41 -3 11 63]]]
Multiplication  [[[104 186  30 144]
  [122  42 166 174]
  [150 150 176  48]
  [  6  44 106   4]]

 [[176  60  76   4]
  [128 120  42  66]
  [152 116  44 178]
  [ 98 182 118  84]]

 [[184 120 160  30]
  [124 124  94 124]
  [102 110 128   6]
  [102  14  42 146]]]
Division  [[[26.  46.5  7.5 36. ]
  [30.5 10.5 41.5 43.5]
  [37.5 37.5 44.  12. ]
  [ 1.5 11.  26.5  1. ]]

 [[44.  15.  19.   1. ]
  [32.  30.  10.5 16.5]
  [38.  29.  11.  44.5]
  [24.5 45.5 29.5 21. ]]

 [[46.  30.  40.   7.5]
  [31.  31.  23.5 31. ]
  [25.5 27.5 32.   1.5]
  [25.5  3.5 10.5 36.5]]]


### Statistical Operations

In [ ]:
np.random.seed(100)
matrix = np.random.randint(1, 100, size=(3,3))
print(matrix)

[[ 9 25 68]
 [88 80 49]
 [11 95 53]]


In [ ]:
# Mean
matrix.mean()

np.float64(53.111111111111114)

In [ ]:
np.median(matrix)

np.float64(53.0)